VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.ssh.insert_key=false

config.vm.define "lamp" do |lamp|
   lamp.vm.box = "bento/ubuntu-20.04"
   lamp.vm.network "forwarded_port", guest: 80, host: 8088
   lamp.vm.network "forwarded_port", guest: 443, host: 9443
end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.sudo = true
  end
end
